# -*- coding: utf-8 -*-
"""borusan_day4_data_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t8VSf-78V0EGSQ-qePbQUkSWx0m8Xx-I
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""##Fiyat aralığı filtreleme"""

df = pd.read_csv("us_used_cars.csv", usecols=["posting_date","price"],parse_dates=["posting_date"])
df = df[(df["price"] >= 500) & (df["price"] <= 200_000)]

df["day"] = df["posting_date"].dt.date
daily = df.groupby("day")["price"].agg(["size","median"]).rename(columns={"size":"count", "median":"med_price"})

daily["count_7d"]= daily["count"].rolling(7, min_periods=3).mean()
daily["price_7d"]= daily["med_price"].rolling(7,min_periods=3).mean()

plt.figure(figsize=(12,5))
plt.plot(daily.index, daily["count"],alpha = 0.5, label="Günlük İlan sayısı")
plt.plot(daily.index, daily["count_7d"], label="7 günlük Ortalama", color="red")
plt.xlabel("Tarih")
plt.ylabel("Adet")
plt.title("7 Günlük İlan Sayısı")
plt.show()

plt.figure(figsize=(12,5))
plt.plot(daily.index, daily["med_price"],alpha = 0.5, label="Günlük Medyan Fiyatları")
plt.plot(daily.index, daily["price_7d"], label="7 günlük Ortalama", color="red")
plt.xlabel("Tarih")
plt.ylabel("USD")
plt.title("Günlük Medyan Fiyatlar")
plt.show()

import seaborn as sns

df = df.dropna(subset=["price"]) # eksik veri temizliği

"""## OUTLIER TESPITI"""

df = df[(df["price"] >= 500) & (df["price"] <= 200_000)]

plt.figure(figsize=(12,6))

sns.kdeplot(df["price"], shade=True, color="steelblue", bw_adjust=0.5)

plt.xlabel("Fiyat(USD)")
plt.ylabel("Yoğunluk")
plt.title("Araç Fiyat Aralık Dağılımı")
plt.legend() # grafiğin bozulmadan ekranda bastırılması
plt.tight_layout() # grafiğin bozulmadan ekranda bastırılması
plt.show()